### ISSUE TITLE
Create an index.js file to import icons

### ISSUE THREAD

**Issue by mvuidev** [metonym/svelvg#3]
Hi, would it be possible to generate an index.js file in the output dir ?
This way we can import icons like this : 

```js
// index.js

export { default as Icon1 } from "./Icon1.svelte";
export { default as Icon2 } from "./Icon2.svelte";

// svelte component

import { Icon1, Icon2 } from "icons/index.js"
```
And thanks for this project !

**Comment by metonym** [comment]
@mvuidev Hi there. Currently, this library does indeed generate an `index.js` that exports all Svelte components.

An example is [svelte-codicons](https://unpkg.com/browse/svelte-codicons@0.4.0/lib/). At the bottom of the page, there is an [`index.js` file](https://unpkg.com/browse/svelte-codicons@0.4.0/lib/index.js).

**Comment by mvuidev** [comment]
@metonym Hey, you're right, there was a problem with one of my svg files and the script throwed an error, that's why the index file wasn't created.

Sorry ! It's all good :)
